version: '3.7'

services:
  pchl:
    image: ghcr.io/polynux/pchl:latest
    volumes:
      - pchl:/app
    environment:
      - PB_API:{{PB_API}}
    ports:
      - "19080:19080"
    deploy:
      update_config:
        order: start-first
volumes:
  pchl: